version: '2'
services:
  www:
    build: ./docker/nginx
    ports:
      - "8080:80"
    links:
      - php
      - db
    volumes:
      - ./vhosts/:/etc/nginx/sites-enabled
      - ./:/www
  php:
    build: ./docker/php
    volumes:
      - ./:/www
    expose:
      - "9000"
    working_dir: /www
    links:
      - db
    environment:
      POSTGRES_PASSWORD: 123qweASD
      POSTGRES_USER: clickmeeting
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
     - /var/lib/pgsql
    environment:
      POSTGRES_PASSWORD: 123qweASD
      POSTGRES_USER: clickmeeting
